model:
  model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
  lora:
    enable: True
    rank: 128
    alpha: 256
    modules:
      - "down_proj"
      - "up_proj"
      - "q_proj"
      - "gate_proj"
      - "q_proj"
      - "k_proj"
      - "v_proj"
    dropout: 0.05
    bias: "none"
    exclude_modules:
      - "mm_projector"
      - "lm_head"
  pretrain_checkpoint_path: null
  mm_vision_hidden_size: 864
  mm_projector_hidden_size: 2048
  image_tokens: 128
data:
  train_conversations_path: "/path/to/conversations/train.csv" # REQUIRED
  eval_conversations_path: "/path/to/conversations/valid.csv" # REQUIRED
  embeddings_path: "/path/to/embeddings" # REQUIRED
  feature_key: "cls"
  system_prompt: ""
  pooling: "none"
  noise_sigma: 0.1
  noise_p: 0.0
train:
  save_safetensors: False
  transformers_cache_dir: null
  optim: "adamw_torch"
  bits: 16
  warmup_ratio: 0.03
  learning_rate: 1e-4
  min_lr: 1e-6
  group_by_modality_length: False
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 1
  eval_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  save_steps: 100
  save_total_limit: null
  weight_decay: 0.0
  logging_steps: 1
  bf16: True
  tf32: True
  model_max_length: 1024
  gradient_checkpointing: True
  dataloader_num_workers: 4
  report_to: "tensorboard"
  logging_dir: "tensorboard"